### ISSUE TITLE
api:W:2021-08-16|23:18:39: determine_default_backend_type: Fallback to SIMULATOR backend as no hardware device was found and no explicit backend is provided (add 'backend=simulator' to the profile argument when allocating DPUs to suppress this message)

### ISSUE THREAD

**Issue by zwjun710** [CMU-SAFARI/prim-benchmarks#1]
Hi CMU-SAFARI team,
When I running run_weak.py or the other file in the SDK, will show:
`api:W:2021-08-16|23:18:39: determine_default_backend_type: Fallback to SIMULATOR backend as no hardware device was found and no explicit backend is provided (add 'backend=simulator' to the profile argument when allocating DPUs to suppress this message)`
Does it matter? Should I change something to fix it?
Looking for your reply, Thanks.

**Comment by el1goluj** [comment]
Hi zwjun710,

Thanks for your question and sorry for the delay. For some reason, I didn't get a notification.

That is just a warning: because you didn't have the actual hardware in the machine, it falls back to the simulator.

As the message says, you can add 'backend=simulator' to the profile argument of dpu_alloc, if the warning bothers you:
dpu_alloc(NR_DPUS, "backend=simulator", &dpu_set);

Thanks,
Juan
